name = "ponto"
compatibility_date = "2024-03-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ponto"
database_id = "d88ca62e-d373-4fed-850c-05991f166528"
